/**
 * Cloudflare Worker for DeepSeek character analysis
 * Handles AI analysis requests and returns Mermaid diagram syntax
 */
import { CHARACTER_ANALYSIS_PROMPT } from '../src/utils/prompt';

interface Env {
  DEEPSEEK_API_KEY: string;
  DIAGRAMS: KVNamespace;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    
    // Handle CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type',
        },
      });
    }

    // Handle GET requests for viewing diagrams
    if (request.method === 'GET') {
      const diagramId = url.pathname.slice(1); // Remove leading /
      
      if (!diagramId) {
        return new Response('Austen CLI - Character Relationship Diagrams', {
          status: 200,
          headers: { 'Content-Type': 'text/plain' },
        });
      }

      // Retrieve diagram from KV storage
      const stored = await env.DIAGRAMS?.get(diagramId);
      
      if (!stored) {
        return new Response('Diagram not found', {
          status: 404,
          headers: { 'Content-Type': 'text/plain' },
        });
      }

      const data = JSON.parse(stored);
      
      // Return HTML page with ASCII art
      const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.bookTitle} - Character Relationships</title>
  <style>
    body {
      font-family: 'Courier New', monospace;
      background: #1a1a1a;
      color: #00ff00;
      padding: 2rem;
      margin: 0;
      line-height: 1.4;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
    }
    h1 {
      color: #00ffff;
      font-size: 1.5rem;
      margin-bottom: 0.5rem;
    }
    .meta {
      color: #888;
      margin-bottom: 2rem;
      font-size: 0.9rem;
    }
    pre {
      background: #0a0a0a;
      padding: 2rem;
      border-radius: 8px;
      overflow-x: auto;
      border: 1px solid #333;
      font-size: 0.9rem;
    }
    .footer {
      margin-top: 2rem;
      text-align: center;
      color: #666;
      font-size: 0.8rem;
    }
    a {
      color: #00ffff;
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>📊 ${data.bookTitle}</h1>
    <div class="meta">by ${data.author}</div>
    <pre>${data.ascii}</pre>
    <div class="footer">
      Generated by <a href="https://github.com/herol3oy/austen-cli" target="_blank">Austen CLI</a>
    </div>
  </div>
</body>
</html>`;

      return new Response(html, {
        status: 200,
        headers: { 'Content-Type': 'text/html' },
      });
    }

    // Only allow POST requests for generation
    if (request.method !== 'POST') {
      return new Response(JSON.stringify({ error: 'Method not allowed' }), {
        status: 405,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
      });
    }

    try {
      // Check if this is an upload request
      if (url.pathname === '/upload') {
        const { diagramId, ascii, bookTitle, author } = await request.json();
        
        if (!diagramId || !ascii) {
          return new Response(
            JSON.stringify({ error: 'Missing diagramId or ascii' }),
            {
              status: 400,
              headers: {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*',
              },
            }
          );
        }

        // Update the stored diagram with ASCII art
        if (env.DIAGRAMS) {
          const existing = await env.DIAGRAMS.get(diagramId);
          if (existing) {
            const data = JSON.parse(existing);
            await env.DIAGRAMS.put(
              diagramId,
              JSON.stringify({
                ...data,
                ascii,
                bookTitle,
                author,
              }),
              { expirationTtl: 60 * 60 * 24 * 30 } // 30 days
            );
          }
        }

        return new Response(
          JSON.stringify({ success: true }),
          {
            status: 200,
            headers: {
              'Content-Type': 'application/json',
              'Access-Control-Allow-Origin': '*',
            },
          }
        );
      }
      // Parse request body
      const { bookTitle, author } = await request.json();

      if (!bookTitle || !author) {
        return new Response(
          JSON.stringify({ error: 'Missing bookTitle or author' }),
          {
            status: 400,
            headers: {
              'Content-Type': 'application/json',
              'Access-Control-Allow-Origin': '*',
            },
          }
        );
      }

      // Check for DeepSeek API key
      if (!env.DEEPSEEK_API_KEY) {
        return new Response(
          JSON.stringify({ error: 'DeepSeek API key not configured' }),
          {
            status: 500,
            headers: {
              'Content-Type': 'application/json',
              'Access-Control-Allow-Origin': '*',
            },
          }
        );
      }

      // Call DeepSeek API
      const response = await fetch('https://api.deepseek.com/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${env.DEEPSEEK_API_KEY}`,
        },
        body: JSON.stringify({
          model: 'deepseek-chat',
          messages: [
            {
              role: 'system',
              content: CHARACTER_ANALYSIS_PROMPT,
            },
            {
              role: 'user',
              content: `Book: ${bookTitle}, Author: ${author}`,
            },
          ],
          temperature: 0.7,
        }),
      });

      if (!response.ok) {
        const error = await response.text();
        console.error('DeepSeek API error:', error);
        return new Response(
          JSON.stringify({ error: 'Failed to analyze characters' }),
          {
            status: response.status,
            headers: {
              'Content-Type': 'application/json',
              'Access-Control-Allow-Origin': '*',
            },
          }
        );
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content?.trim();

      if (!content) {
        return new Response(
          JSON.stringify({ error: 'No response from AI' }),
          {
            status: 500,
            headers: {
              'Content-Type': 'application/json',
              'Access-Control-Allow-Origin': '*',
            },
          }
        );
      }

      // Generate unique ID for this diagram
      const diagramId = crypto.randomUUID();
      const shareUrl = `${url.origin}/${diagramId}`;

      // Store diagram in KV (expires after 30 days)
      if (env.DIAGRAMS) {
        await env.DIAGRAMS.put(
          diagramId,
          JSON.stringify({
            bookTitle,
            author,
            mermaidSyntax: content,
            ascii: '', // Will be populated by CLI
            createdAt: new Date().toISOString(),
          }),
          { expirationTtl: 60 * 60 * 24 * 30 } // 30 days
        );
      }

      // Return the Mermaid syntax and share URL
      return new Response(
        JSON.stringify({ 
          mermaidSyntax: content,
          shareUrl,
          diagramId
        }),
        {
          status: 200,
          headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*',
          },
        }
      );
    } catch (error) {
      console.error('Worker error:', error);
      return new Response(
        JSON.stringify({ error: 'Internal server error' }),
        {
          status: 500,
          headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*',
          },
        }
      );
    }
  },
} 
